### PR TITLE
[xamarin.ios] update quickstart to Unified (64-bit)

### PR DESCRIPTION
**Pull request by conceptdev**
based on a diff after updating a template downloaded from manage.windowsazure.com - hard to test though. i would like to do a subsequent PR with updated resources for iPhone 6/Plus.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@conceptdev__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by conceptdev** [comment]
whoops, the .tt files are incorrect

**Comment by phvannor** [comment]
We are moving our QuickStarts to live on the https://github.com/Azure/azure-mobile-services-quickstarts repo.  When you reopen a PR, can you put it against Master there?

**Comment by conceptdev** [comment]
@phvannor done -> https://github.com/Azure/azure-mobile-services-quickstarts/pull/12

**Pull request closed without merging**
