### PR TITLE
Support for dynamic iOS frameworks

### PR DESCRIPTION
**Pull request by fonkadelic**
With Xcode 6, Apple has added iOS framework support for apps targeting iOS8 or later.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@fonkadelic__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@fonkadelic__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by damienpontifex** [comment]
It would be great to also include a cocoapod podspec with this. Now they support dynamic frameworks, it makes it pretty easy to utilise in a project. As an example, I have a private podspec in my project that could be incorporated that looks as such (obviously change the source from my fork to the main repo if including it):

```ruby
Pod::Spec.new do |s|
  s.name         = "WindowsAzureMobileServices"
  s.version      = "1.2.1"
  s.summary      = "Integrate with Azure Mobile Services"
  s.homepage     = "https://github.com/Azure/azure-mobile-services"
  s.license      = { 
    :type => "Apache", 
    :file => "LICENSE.txt" 
  }
  s.author       = { 
    "Damien Pontifex" => "damien.pontifex@gmail.com" 
  }
  s.platform     = :ios, "8.0"
  s.source       = { 
    :git => "https://github.com/damienpontifex/azure-mobile-services.git", 
    :branch => "MobileApp" 
  }
  s.requires_arc = true
  s.source_files = "Classes", "sdk/iOS/src/**/*.{h,m}"
  s.public_header_files = [
  	"sdk/iOS/src/WindowsAzureMobileServices.h",
  	"sdk/iOS/src/MSQueryResult.h",
  	"sdk/iOS/src/MSLoginController.h",
  	"sdk/iOS/src/MSClient.h",
  	"sdk/iOS/src/MSQuery.h",
  	"sdk/iOS/src/MSTableOperation.h",
  	"sdk/iOS/src/MSUser.h",
  	"sdk/iOS/src/MSSyncContext.h",
  	"sdk/iOS/src/MSTableOperationError.h"
  	"sdk/iOS/src/MSFilter.h"
  	"sdk/iOS/src/MSCoreDataStore.h",
  	"sdk/iOS/src/BlockDefinitions.h",
  	"sdk/iOS/src/MSDateOffset.h",
  	"sdk/iOS/src/MSPush.h",
  	"sdk/iOS/src/MSError.h",
  	"sdk/iOS/src/MSSyncContextReadResult.h"
  ]
  s.requires_arc = true
end
```

**Comment by phvannor** [comment]
@fonkadelic how does the new dynamic fw compare to our old built FW files?  Will I be able to just change the one I'm using and my app will just work now (assuming I target iOS 8.0+)?

**Comment by damienpontifex** [comment]
I have done this with a static library I was creating and converted it to a framework target. Replaced the library link and no problems.

Also you get module support with the new frameworks that I don't think is currently configured with the FW build script. Plus it may make things easier in the future as it will reduce the number of targets by removing the static library and build script.

**Comment by fonkadelic** [comment]
@phvannor The framework script currently used is not a **dynamic** framework and some kind of a hack. It's basically just a nicer wrapper around a **static** lib. 

For more Information about Apples dynamic frameworks check: https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPFrameworks/Frameworks.html#//apple_ref/doc/uid/10000183-SW1

And yes, you will be able to just switch over to dynamic frameworks for iOS 8.0 + apps. (For example, this can be useful if you are working with app extensions.)

**Comment by phvannor** [comment]
I think we may want to tweak version numbering, etc before final use & incorporation into a pod specs & releases, but am ok taking this as is atm.

**Pull request merged**
