### PR TITLE
Fix NSNull templateName

### PR DESCRIPTION
**Pull request by brondavies**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@brondavies__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@brondavies__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by phvannor** [comment]
Code looks good, I take it this is needed as a null is being returned by the server for template name on list registrations?

**Comment by brondavies** [comment]
Yes, I think that's why it gets that sometimes.

**Pull request merged**
